# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "quantal"
  config.vm.box_url = "https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box"

  config.vm.hostname = "presentr"
#  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", :adapter => 2

  config.vm.synced_folder "..", "/presentr"
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.network :forwarded_port, guest: 80,   host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 8000, host: 8000, auto_correct: true

  config.vm.network :forwarded_port, guest: 1337, host: 1337, auto_correct: true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct: true

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpus", 2,
      "--memory", "2048",
      "--name", "Presentr",
      "--nicpromisc2", "allow-all"
    ]
  end
end
